source 'https://rubygems.org'

ruby '~> 3.3.4'

gem 'sinatra'
gem 'launchdarkly-server-sdk', '~> 8.0'
gem 'launchdarkly-observability', path: '../../../../sdk/@launchdarkly/observability-ruby'

gem "rackup", "~> 2.2"
gem "puma", "~> 6.6"
