// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class LDInstrumentationOptions {
  LDInstrumentationOptions({
    this.networkRequests,
    this.launchTimes,
  });

  bool? networkRequests;

  bool? launchTimes;

  List<Object?> _toList() {
    return <Object?>[
      networkRequests,
      launchTimes,
    ];
  }

  Object encode() {
    return _toList();  }

  static LDInstrumentationOptions decode(Object result) {
    result as List<Object?>;
    return LDInstrumentationOptions(
      networkRequests: result[0] as bool?,
      launchTimes: result[1] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDInstrumentationOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class LDObservabilityOptions {
  LDObservabilityOptions({
    this.isEnabled,
    this.serviceName,
    this.serviceVersion,
    this.otlpEndpoint,
    this.backendUrl,
    this.contextFriendlyName,
    this.attributes,
    this.instrumentation,
  });

  bool? isEnabled;

  String? serviceName;

  String? serviceVersion;

  String? otlpEndpoint;

  String? backendUrl;

  String? contextFriendlyName;

  Map<String, Object?>? attributes;

  LDInstrumentationOptions? instrumentation;

  List<Object?> _toList() {
    return <Object?>[
      isEnabled,
      serviceName,
      serviceVersion,
      otlpEndpoint,
      backendUrl,
      contextFriendlyName,
      attributes,
      instrumentation,
    ];
  }

  Object encode() {
    return _toList();  }

  static LDObservabilityOptions decode(Object result) {
    result as List<Object?>;
    return LDObservabilityOptions(
      isEnabled: result[0] as bool?,
      serviceName: result[1] as String?,
      serviceVersion: result[2] as String?,
      otlpEndpoint: result[3] as String?,
      backendUrl: result[4] as String?,
      contextFriendlyName: result[5] as String?,
      attributes: (result[6] as Map<Object?, Object?>?)?.cast<String, Object?>(),
      instrumentation: result[7] as LDInstrumentationOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDObservabilityOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class LDPrivacyOptions {
  LDPrivacyOptions({
    this.maskTextInputs,
    this.maskWebViews,
    this.maskLabels,
    this.maskImages,
    this.minimumAlpha,
  });

  bool? maskTextInputs;

  bool? maskWebViews;

  bool? maskLabels;

  bool? maskImages;

  double? minimumAlpha;

  List<Object?> _toList() {
    return <Object?>[
      maskTextInputs,
      maskWebViews,
      maskLabels,
      maskImages,
      minimumAlpha,
    ];
  }

  Object encode() {
    return _toList();  }

  static LDPrivacyOptions decode(Object result) {
    result as List<Object?>;
    return LDPrivacyOptions(
      maskTextInputs: result[0] as bool?,
      maskWebViews: result[1] as bool?,
      maskLabels: result[2] as bool?,
      maskImages: result[3] as bool?,
      minimumAlpha: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDPrivacyOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class LDSessionReplayOptions {
  LDSessionReplayOptions({
    this.isEnabled,
    this.serviceName,
    this.privacy,
  });

  bool? isEnabled;

  String? serviceName;

  LDPrivacyOptions? privacy;

  List<Object?> _toList() {
    return <Object?>[
      isEnabled,
      serviceName,
      privacy,
    ];
  }

  Object encode() {
    return _toList();  }

  static LDSessionReplayOptions decode(Object result) {
    result as List<Object?>;
    return LDSessionReplayOptions(
      isEnabled: result[0] as bool?,
      serviceName: result[1] as String?,
      privacy: result[2] as LDPrivacyOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDSessionReplayOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class LDStartResult {
  LDStartResult({
    this.nativeVersion,
  });

  String? nativeVersion;

  List<Object?> _toList() {
    return <Object?>[
      nativeVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static LDStartResult decode(Object result) {
    result as List<Object?>;
    return LDStartResult(
      nativeVersion: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDStartResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LDInstrumentationOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is LDObservabilityOptions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is LDPrivacyOptions) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is LDSessionReplayOptions) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is LDStartResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return LDInstrumentationOptions.decode(readValue(buffer)!);
      case 130: 
        return LDObservabilityOptions.decode(readValue(buffer)!);
      case 131: 
        return LDPrivacyOptions.decode(readValue(buffer)!);
      case 132: 
        return LDSessionReplayOptions.decode(readValue(buffer)!);
      case 133: 
        return LDStartResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LDNativeApi {
  /// Constructor for [LDNativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LDNativeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<LDStartResult> start(String mobileKey, LDObservabilityOptions observability, LDSessionReplayOptions replay, String observabilityVersion) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.launchdarkly_flutter_session_replay.LDNativeApi.start$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mobileKey, observability, replay, observabilityVersion]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as LDStartResult?)!;
    }
  }
}
