name: "Continuous Integration"

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]

jobs:
  tests:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: "opentelemetry"
          php-version: "8.2"
          tools: composer

      - name: Install Dependencies
        uses: ramsey/composer-install@v2
        with:
            composer-options: "--ansi --no-interaction --no-progress --prefer-dist"

      - name: Run Tests
        run: composer test