# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in launchdarkly-observability.gemspec
gemspec

group :development, :test do
  gem 'minitest', '~> 5.0'
  gem 'rake', '~> 13.0'
  gem 'rubocop', '~> 1.0'
end

# Optional: Rails integration testing
group :test do
  gem 'rails', '>= 6.0'
  gem 'webmock', '~> 3.0'
end
