// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct LDInstrumentationOptions: Hashable {
  var networkRequests: Bool? = nil
  var launchTimes: Bool? = nil
  var crashReporting: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDInstrumentationOptions? {
    let networkRequests: Bool? = nilOrValue(pigeonVar_list[0])
    let launchTimes: Bool? = nilOrValue(pigeonVar_list[1])
    let crashReporting: Bool? = nilOrValue(pigeonVar_list[2])

    return LDInstrumentationOptions(
      networkRequests: networkRequests,
      launchTimes: launchTimes,
      crashReporting: crashReporting
    )
  }
  func toList() -> [Any?] {
    return [
      networkRequests,
      launchTimes,
      crashReporting,
    ]
  }
  static func == (lhs: LDInstrumentationOptions, rhs: LDInstrumentationOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDTracesOptions: Hashable {
  var includeErrors: Bool? = nil
  var includeSpans: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDTracesOptions? {
    let includeErrors: Bool? = nilOrValue(pigeonVar_list[0])
    let includeSpans: Bool? = nilOrValue(pigeonVar_list[1])

    return LDTracesOptions(
      includeErrors: includeErrors,
      includeSpans: includeSpans
    )
  }
  func toList() -> [Any?] {
    return [
      includeErrors,
      includeSpans,
    ]
  }
  static func == (lhs: LDTracesOptions, rhs: LDTracesOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDAnalyticsOptions: Hashable {
  var taps: Bool? = nil
  var pageViews: Bool? = nil
  var trackEvents: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDAnalyticsOptions? {
    let taps: Bool? = nilOrValue(pigeonVar_list[0])
    let pageViews: Bool? = nilOrValue(pigeonVar_list[1])
    let trackEvents: Bool? = nilOrValue(pigeonVar_list[2])

    return LDAnalyticsOptions(
      taps: taps,
      pageViews: pageViews,
      trackEvents: trackEvents
    )
  }
  func toList() -> [Any?] {
    return [
      taps,
      pageViews,
      trackEvents,
    ]
  }
  static func == (lhs: LDAnalyticsOptions, rhs: LDAnalyticsOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDObservabilityOptions: Hashable {
  var isEnabled: Bool? = nil
  var serviceName: String? = nil
  var serviceVersion: String? = nil
  var otlpEndpoint: String? = nil
  var backendUrl: String? = nil
  var contextFriendlyName: String? = nil
  var attributes: [String: Any?]? = nil
  var customHeaders: [String: String]? = nil
  var sessionBackgroundTimeoutMillis: Int64? = nil
  var logsApiLevel: Int64? = nil
  var traces: LDTracesOptions? = nil
  var metricsEnabled: Bool? = nil
  var analytics: LDAnalyticsOptions? = nil
  var instrumentation: LDInstrumentationOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDObservabilityOptions? {
    let isEnabled: Bool? = nilOrValue(pigeonVar_list[0])
    let serviceName: String? = nilOrValue(pigeonVar_list[1])
    let serviceVersion: String? = nilOrValue(pigeonVar_list[2])
    let otlpEndpoint: String? = nilOrValue(pigeonVar_list[3])
    let backendUrl: String? = nilOrValue(pigeonVar_list[4])
    let contextFriendlyName: String? = nilOrValue(pigeonVar_list[5])
    let attributes: [String: Any?]? = nilOrValue(pigeonVar_list[6])
    let customHeaders: [String: String]? = nilOrValue(pigeonVar_list[7])
    let sessionBackgroundTimeoutMillis: Int64? = nilOrValue(pigeonVar_list[8])
    let logsApiLevel: Int64? = nilOrValue(pigeonVar_list[9])
    let traces: LDTracesOptions? = nilOrValue(pigeonVar_list[10])
    let metricsEnabled: Bool? = nilOrValue(pigeonVar_list[11])
    let analytics: LDAnalyticsOptions? = nilOrValue(pigeonVar_list[12])
    let instrumentation: LDInstrumentationOptions? = nilOrValue(pigeonVar_list[13])

    return LDObservabilityOptions(
      isEnabled: isEnabled,
      serviceName: serviceName,
      serviceVersion: serviceVersion,
      otlpEndpoint: otlpEndpoint,
      backendUrl: backendUrl,
      contextFriendlyName: contextFriendlyName,
      attributes: attributes,
      customHeaders: customHeaders,
      sessionBackgroundTimeoutMillis: sessionBackgroundTimeoutMillis,
      logsApiLevel: logsApiLevel,
      traces: traces,
      metricsEnabled: metricsEnabled,
      analytics: analytics,
      instrumentation: instrumentation
    )
  }
  func toList() -> [Any?] {
    return [
      isEnabled,
      serviceName,
      serviceVersion,
      otlpEndpoint,
      backendUrl,
      contextFriendlyName,
      attributes,
      customHeaders,
      sessionBackgroundTimeoutMillis,
      logsApiLevel,
      traces,
      metricsEnabled,
      analytics,
      instrumentation,
    ]
  }
  static func == (lhs: LDObservabilityOptions, rhs: LDObservabilityOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDPrivacyOptions: Hashable {
  var maskTextInputs: Bool? = nil
  var maskWebViews: Bool? = nil
  var maskLabels: Bool? = nil
  var maskImages: Bool? = nil
  var minimumAlpha: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDPrivacyOptions? {
    let maskTextInputs: Bool? = nilOrValue(pigeonVar_list[0])
    let maskWebViews: Bool? = nilOrValue(pigeonVar_list[1])
    let maskLabels: Bool? = nilOrValue(pigeonVar_list[2])
    let maskImages: Bool? = nilOrValue(pigeonVar_list[3])
    let minimumAlpha: Double? = nilOrValue(pigeonVar_list[4])

    return LDPrivacyOptions(
      maskTextInputs: maskTextInputs,
      maskWebViews: maskWebViews,
      maskLabels: maskLabels,
      maskImages: maskImages,
      minimumAlpha: minimumAlpha
    )
  }
  func toList() -> [Any?] {
    return [
      maskTextInputs,
      maskWebViews,
      maskLabels,
      maskImages,
      minimumAlpha,
    ]
  }
  static func == (lhs: LDPrivacyOptions, rhs: LDPrivacyOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDSessionReplayOptions: Hashable {
  var isEnabled: Bool? = nil
  var serviceName: String? = nil
  var frameRate: Double? = nil
  var privacy: LDPrivacyOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDSessionReplayOptions? {
    let isEnabled: Bool? = nilOrValue(pigeonVar_list[0])
    let serviceName: String? = nilOrValue(pigeonVar_list[1])
    let frameRate: Double? = nilOrValue(pigeonVar_list[2])
    let privacy: LDPrivacyOptions? = nilOrValue(pigeonVar_list[3])

    return LDSessionReplayOptions(
      isEnabled: isEnabled,
      serviceName: serviceName,
      frameRate: frameRate,
      privacy: privacy
    )
  }
  func toList() -> [Any?] {
    return [
      isEnabled,
      serviceName,
      frameRate,
      privacy,
    ]
  }
  static func == (lhs: LDSessionReplayOptions, rhs: LDSessionReplayOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDStartResult: Hashable {
  var nativeVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDStartResult? {
    let nativeVersion: String? = nilOrValue(pigeonVar_list[0])

    return LDStartResult(
      nativeVersion: nativeVersion
    )
  }
  func toList() -> [Any?] {
    return [
      nativeVersion
    ]
  }
  static func == (lhs: LDStartResult, rhs: LDStartResult) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// An event recorded on a span, forwarded to the native tracer.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LDSpanEvent: Hashable {
  var name: String? = nil
  var attributes: [String: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDSpanEvent? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let attributes: [String: Any?]? = nilOrValue(pigeonVar_list[1])

    return LDSpanEvent(
      name: name,
      attributes: attributes
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      attributes,
    ]
  }
  static func == (lhs: LDSpanEvent, rhs: LDSpanEvent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// A completed Dart span, forwarded to the native tracer so the native
/// pipeline re-creates it (stamping `session.id`, sampling, batching).
///
/// Mirrors the data carried by MAUI's `TraceBuilderAdapter`
/// (`sdk/@launchdarkly/mobile-dotnet/observability/bridge/TraceBuilderAdapter.cs`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct LDSpanData: Hashable {
  var name: String? = nil
  /// Span start as epoch seconds.
  var startTimeSeconds: Double? = nil
  /// Span end as epoch seconds.
  var endTimeSeconds: Double? = nil
  /// 32-char hex trace id.
  var traceId: String? = nil
  /// 16-char hex span id.
  var spanId: String? = nil
  /// 16-char hex parent span id, or empty for a root span.
  var parentSpanId: String? = nil
  var attributes: [String: Any?]? = nil
  var events: [LDSpanEvent?]? = nil
  /// 0 = unset, 1 = ok, 2 = error.
  var statusCode: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDSpanData? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let startTimeSeconds: Double? = nilOrValue(pigeonVar_list[1])
    let endTimeSeconds: Double? = nilOrValue(pigeonVar_list[2])
    let traceId: String? = nilOrValue(pigeonVar_list[3])
    let spanId: String? = nilOrValue(pigeonVar_list[4])
    let parentSpanId: String? = nilOrValue(pigeonVar_list[5])
    let attributes: [String: Any?]? = nilOrValue(pigeonVar_list[6])
    let events: [LDSpanEvent?]? = nilOrValue(pigeonVar_list[7])
    let statusCode: Int64? = nilOrValue(pigeonVar_list[8])

    return LDSpanData(
      name: name,
      startTimeSeconds: startTimeSeconds,
      endTimeSeconds: endTimeSeconds,
      traceId: traceId,
      spanId: spanId,
      parentSpanId: parentSpanId,
      attributes: attributes,
      events: events,
      statusCode: statusCode
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      startTimeSeconds,
      endTimeSeconds,
      traceId,
      spanId,
      parentSpanId,
      attributes,
      events,
      statusCode,
    ]
  }
  static func == (lhs: LDSpanData, rhs: LDSpanData) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// A log record forwarded to the native logger so it is emitted as a real
/// OpenTelemetry `LogRecord` (stamped with `session.id` and correlated with
/// the active span).
///
/// Generated class from Pigeon that represents data sent in messages.
struct LDLogRecord: Hashable {
  var message: String? = nil
  /// OpenTelemetry severity number (e.g. 9 = INFO, 13 = WARN, 17 = ERROR).
  var severityNumber: Int64? = nil
  /// 32-char hex trace id of the active span, or null when none.
  var traceId: String? = nil
  /// 16-char hex span id of the active span, or null when none.
  var spanId: String? = nil
  var attributes: [String: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDLogRecord? {
    let message: String? = nilOrValue(pigeonVar_list[0])
    let severityNumber: Int64? = nilOrValue(pigeonVar_list[1])
    let traceId: String? = nilOrValue(pigeonVar_list[2])
    let spanId: String? = nilOrValue(pigeonVar_list[3])
    let attributes: [String: Any?]? = nilOrValue(pigeonVar_list[4])

    return LDLogRecord(
      message: message,
      severityNumber: severityNumber,
      traceId: traceId,
      spanId: spanId,
      attributes: attributes
    )
  }
  func toList() -> [Any?] {
    return [
      message,
      severityNumber,
      traceId,
      spanId,
      attributes,
    ]
  }
  static func == (lhs: LDLogRecord, rhs: LDLogRecord) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return LDInstrumentationOptions.fromList(self.readValue() as! [Any?])
    case 130:
      return LDTracesOptions.fromList(self.readValue() as! [Any?])
    case 131:
      return LDAnalyticsOptions.fromList(self.readValue() as! [Any?])
    case 132:
      return LDObservabilityOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return LDPrivacyOptions.fromList(self.readValue() as! [Any?])
    case 134:
      return LDSessionReplayOptions.fromList(self.readValue() as! [Any?])
    case 135:
      return LDStartResult.fromList(self.readValue() as! [Any?])
    case 136:
      return LDSpanEvent.fromList(self.readValue() as! [Any?])
    case 137:
      return LDSpanData.fromList(self.readValue() as! [Any?])
    case 138:
      return LDLogRecord.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LDInstrumentationOptions {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? LDTracesOptions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LDAnalyticsOptions {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? LDObservabilityOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? LDPrivacyOptions {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? LDSessionReplayOptions {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? LDStartResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? LDSpanEvent {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? LDSpanData {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? LDLogRecord {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LDNativeApi {
  func start(mobileKey: String, observability: LDObservabilityOptions, replay: LDSessionReplayOptions, observabilityVersion: String, completion: @escaping (Result<LDStartResult, Error>) -> Void)
  /// Forwards completed Dart spans to the native tracer. Native re-creates each
  /// span so the native pipeline stamps `session.id` and exports it.
  func exportSpans(spans: [LDSpanData]) throws
  /// Forwards a Dart log to the native logger so it is emitted as a native
  /// `LogRecord` with `session.id` and trace/span correlation.
  func recordLog(log: LDLogRecord) throws
  /// Forwards a custom track event to the native observability SDK so it emits
  /// the native `track` span (gated by `analytics.trackEvents`) and the Session
  /// Replay `Track` timeline event (always). `data` carries the optional event
  /// payload as a JSON object. `contextKeys` carries the evaluation context's
  /// kind -> key pairs (from the LaunchDarkly client's `afterTrack` hook) so the
  /// native `track` span is attributed to the same context the web SDK records;
  /// only the span is annotated, not the Session Replay `Track` payload.
  func track(key: String, data: [String: Any?]?, metricValue: Double?, contextKeys: [String: String]?) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LDNativeApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LDNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LDNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mobileKeyArg = args[0] as! String
        let observabilityArg = args[1] as! LDObservabilityOptions
        let replayArg = args[2] as! LDSessionReplayOptions
        let observabilityVersionArg = args[3] as! String
        api.start(mobileKey: mobileKeyArg, observability: observabilityArg, replay: replayArg, observabilityVersion: observabilityVersionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// Forwards completed Dart spans to the native tracer. Native re-creates each
    /// span so the native pipeline stamps `session.id` and exports it.
    let exportSpansChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.exportSpans\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportSpansChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let spansArg = args[0] as! [LDSpanData]
        do {
          try api.exportSpans(spans: spansArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      exportSpansChannel.setMessageHandler(nil)
    }
    /// Forwards a Dart log to the native logger so it is emitted as a native
    /// `LogRecord` with `session.id` and trace/span correlation.
    let recordLogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.recordLog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recordLogChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let logArg = args[0] as! LDLogRecord
        do {
          try api.recordLog(log: logArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      recordLogChannel.setMessageHandler(nil)
    }
    /// Forwards a custom track event to the native observability SDK so it emits
    /// the native `track` span (gated by `analytics.trackEvents`) and the Session
    /// Replay `Track` timeline event (always). `data` carries the optional event
    /// payload as a JSON object. `contextKeys` carries the evaluation context's
    /// kind -> key pairs (from the LaunchDarkly client's `afterTrack` hook) so the
    /// native `track` span is attributed to the same context the web SDK records;
    /// only the span is annotated, not the Session Replay `Track` payload.
    let trackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.track\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let dataArg: [String: Any?]? = nilOrValue(args[1])
        let metricValueArg: Double? = nilOrValue(args[2])
        let contextKeysArg: [String: String]? = nilOrValue(args[3])
        do {
          try api.track(key: keyArg, data: dataArg, metricValue: metricValueArg, contextKeys: contextKeysArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackChannel.setMessageHandler(nil)
    }
  }
}
