// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct LDInstrumentationOptions: Hashable {
  var networkRequests: Bool? = nil
  var launchTimes: Bool? = nil
  var crashReporting: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDInstrumentationOptions? {
    let networkRequests: Bool? = nilOrValue(pigeonVar_list[0])
    let launchTimes: Bool? = nilOrValue(pigeonVar_list[1])
    let crashReporting: Bool? = nilOrValue(pigeonVar_list[2])

    return LDInstrumentationOptions(
      networkRequests: networkRequests,
      launchTimes: launchTimes,
      crashReporting: crashReporting
    )
  }
  func toList() -> [Any?] {
    return [
      networkRequests,
      launchTimes,
      crashReporting,
    ]
  }
  static func == (lhs: LDInstrumentationOptions, rhs: LDInstrumentationOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDTracesOptions: Hashable {
  var includeErrors: Bool? = nil
  var includeSpans: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDTracesOptions? {
    let includeErrors: Bool? = nilOrValue(pigeonVar_list[0])
    let includeSpans: Bool? = nilOrValue(pigeonVar_list[1])

    return LDTracesOptions(
      includeErrors: includeErrors,
      includeSpans: includeSpans
    )
  }
  func toList() -> [Any?] {
    return [
      includeErrors,
      includeSpans,
    ]
  }
  static func == (lhs: LDTracesOptions, rhs: LDTracesOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDProductAnalyticsOptions: Hashable {
  var taps: Bool? = nil
  var pageViews: Bool? = nil
  var trackEvents: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDProductAnalyticsOptions? {
    let taps: Bool? = nilOrValue(pigeonVar_list[0])
    let pageViews: Bool? = nilOrValue(pigeonVar_list[1])
    let trackEvents: Bool? = nilOrValue(pigeonVar_list[2])

    return LDProductAnalyticsOptions(
      taps: taps,
      pageViews: pageViews,
      trackEvents: trackEvents
    )
  }
  func toList() -> [Any?] {
    return [
      taps,
      pageViews,
      trackEvents,
    ]
  }
  static func == (lhs: LDProductAnalyticsOptions, rhs: LDProductAnalyticsOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDObservabilityOptions: Hashable {
  var isEnabled: Bool? = nil
  var serviceName: String? = nil
  var serviceVersion: String? = nil
  var otlpEndpoint: String? = nil
  var backendUrl: String? = nil
  var contextFriendlyName: String? = nil
  var attributes: [String: Any?]? = nil
  var customHeaders: [String: String]? = nil
  var sessionBackgroundTimeoutMillis: Int64? = nil
  var logsApiLevel: Int64? = nil
  var traces: LDTracesOptions? = nil
  var metricsEnabled: Bool? = nil
  var productAnalytics: LDProductAnalyticsOptions? = nil
  var instrumentation: LDInstrumentationOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDObservabilityOptions? {
    let isEnabled: Bool? = nilOrValue(pigeonVar_list[0])
    let serviceName: String? = nilOrValue(pigeonVar_list[1])
    let serviceVersion: String? = nilOrValue(pigeonVar_list[2])
    let otlpEndpoint: String? = nilOrValue(pigeonVar_list[3])
    let backendUrl: String? = nilOrValue(pigeonVar_list[4])
    let contextFriendlyName: String? = nilOrValue(pigeonVar_list[5])
    let attributes: [String: Any?]? = nilOrValue(pigeonVar_list[6])
    let customHeaders: [String: String]? = nilOrValue(pigeonVar_list[7])
    let sessionBackgroundTimeoutMillis: Int64? = nilOrValue(pigeonVar_list[8])
    let logsApiLevel: Int64? = nilOrValue(pigeonVar_list[9])
    let traces: LDTracesOptions? = nilOrValue(pigeonVar_list[10])
    let metricsEnabled: Bool? = nilOrValue(pigeonVar_list[11])
    let productAnalytics: LDProductAnalyticsOptions? = nilOrValue(pigeonVar_list[12])
    let instrumentation: LDInstrumentationOptions? = nilOrValue(pigeonVar_list[13])

    return LDObservabilityOptions(
      isEnabled: isEnabled,
      serviceName: serviceName,
      serviceVersion: serviceVersion,
      otlpEndpoint: otlpEndpoint,
      backendUrl: backendUrl,
      contextFriendlyName: contextFriendlyName,
      attributes: attributes,
      customHeaders: customHeaders,
      sessionBackgroundTimeoutMillis: sessionBackgroundTimeoutMillis,
      logsApiLevel: logsApiLevel,
      traces: traces,
      metricsEnabled: metricsEnabled,
      productAnalytics: productAnalytics,
      instrumentation: instrumentation
    )
  }
  func toList() -> [Any?] {
    return [
      isEnabled,
      serviceName,
      serviceVersion,
      otlpEndpoint,
      backendUrl,
      contextFriendlyName,
      attributes,
      customHeaders,
      sessionBackgroundTimeoutMillis,
      logsApiLevel,
      traces,
      metricsEnabled,
      productAnalytics,
      instrumentation,
    ]
  }
  static func == (lhs: LDObservabilityOptions, rhs: LDObservabilityOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDPrivacyOptions: Hashable {
  var maskTextInputs: Bool? = nil
  var maskWebViews: Bool? = nil
  var maskLabels: Bool? = nil
  var maskImages: Bool? = nil
  var minimumAlpha: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDPrivacyOptions? {
    let maskTextInputs: Bool? = nilOrValue(pigeonVar_list[0])
    let maskWebViews: Bool? = nilOrValue(pigeonVar_list[1])
    let maskLabels: Bool? = nilOrValue(pigeonVar_list[2])
    let maskImages: Bool? = nilOrValue(pigeonVar_list[3])
    let minimumAlpha: Double? = nilOrValue(pigeonVar_list[4])

    return LDPrivacyOptions(
      maskTextInputs: maskTextInputs,
      maskWebViews: maskWebViews,
      maskLabels: maskLabels,
      maskImages: maskImages,
      minimumAlpha: minimumAlpha
    )
  }
  func toList() -> [Any?] {
    return [
      maskTextInputs,
      maskWebViews,
      maskLabels,
      maskImages,
      minimumAlpha,
    ]
  }
  static func == (lhs: LDPrivacyOptions, rhs: LDPrivacyOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDSessionReplayOptions: Hashable {
  var isEnabled: Bool? = nil
  var serviceName: String? = nil
  var frameRate: Double? = nil
  var privacy: LDPrivacyOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDSessionReplayOptions? {
    let isEnabled: Bool? = nilOrValue(pigeonVar_list[0])
    let serviceName: String? = nilOrValue(pigeonVar_list[1])
    let frameRate: Double? = nilOrValue(pigeonVar_list[2])
    let privacy: LDPrivacyOptions? = nilOrValue(pigeonVar_list[3])

    return LDSessionReplayOptions(
      isEnabled: isEnabled,
      serviceName: serviceName,
      frameRate: frameRate,
      privacy: privacy
    )
  }
  func toList() -> [Any?] {
    return [
      isEnabled,
      serviceName,
      frameRate,
      privacy,
    ]
  }
  static func == (lhs: LDSessionReplayOptions, rhs: LDSessionReplayOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LDStartResult: Hashable {
  var nativeVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LDStartResult? {
    let nativeVersion: String? = nilOrValue(pigeonVar_list[0])

    return LDStartResult(
      nativeVersion: nativeVersion
    )
  }
  func toList() -> [Any?] {
    return [
      nativeVersion
    ]
  }
  static func == (lhs: LDStartResult, rhs: LDStartResult) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return LDInstrumentationOptions.fromList(self.readValue() as! [Any?])
    case 130:
      return LDTracesOptions.fromList(self.readValue() as! [Any?])
    case 131:
      return LDProductAnalyticsOptions.fromList(self.readValue() as! [Any?])
    case 132:
      return LDObservabilityOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return LDPrivacyOptions.fromList(self.readValue() as! [Any?])
    case 134:
      return LDSessionReplayOptions.fromList(self.readValue() as! [Any?])
    case 135:
      return LDStartResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LDInstrumentationOptions {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? LDTracesOptions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LDProductAnalyticsOptions {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? LDObservabilityOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? LDPrivacyOptions {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? LDSessionReplayOptions {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? LDStartResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LDNativeApi {
  func start(mobileKey: String, observability: LDObservabilityOptions, replay: LDSessionReplayOptions, observabilityVersion: String, completion: @escaping (Result<LDStartResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LDNativeApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LDNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LDNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mobileKeyArg = args[0] as! String
        let observabilityArg = args[1] as! LDObservabilityOptions
        let replayArg = args[2] as! LDSessionReplayOptions
        let observabilityVersionArg = args[3] as! String
        api.start(mobileKey: mobileKeyArg, observability: observabilityArg, replay: replayArg, observabilityVersion: observabilityVersionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
  }
}
