import { GraphQLClient } from 'graphql-request'
import stringify from 'json-stringify-safe'
import { UPLOAD_TIMEOUT } from '../constants/sessions'
import {
	getSdk,
	PushPayloadMutationVariables,
	Sdk,
} from '../graph/generated/operations'
import { payloadToBase64 } from '../utils/payload'
import { ReplayEventsInput } from '../graph/generated/schemas'
import { Logger } from '../logger'
import { MetricCategory } from '../types/client'
import { isErrorRecoverable } from '../utils/error-recoverability'
import { getGraphQLRequestWrapper } from '../utils/graph'
import {
	MAX_PUBLIC_GRAPH_RETRY_ATTEMPTS,
	NON_SERIALIZABLE_PROPS,
	PROPERTY_MAX_LENGTH,
} from './constants'
import {
	AsyncEventsMessage,
	AsyncEventsResponse,
	FeedbackMessage,
	HighlightClientWorkerParams,
	HighlightClientWorkerResponse,
	IdentifyMessage,
	MessageType,
	MetricsMessage,
	PropertiesMessage,
	StopEventResponse,
	StopReason,
} from './types'

export interface HighlightClientRequestWorker {
	postMessage: (message: HighlightClientWorkerParams) => void
	onmessage: (message: MessageEvent<HighlightClientWorkerResponse>) => void
}

interface HighlightClientResponseWorker {
	onmessage:
		| null
		| ((message: MessageEvent<HighlightClientWorkerParams>) => void)

	postMessage(e: HighlightClientWorkerResponse): void
}

// `as any` because: https://github.com/Microsoft/TypeScript/issues/20595
const worker: HighlightClientResponseWorker = self as any

function stringifyProperties(
	properties_object: any,
	type: 'session' | 'track' | 'user',
) {
	const stringifiedObj: any = {}
	const invalidTypes: any[] = []
	const tooLong: any[] = []
	for (const [key, value] of Object.entries(properties_object)) {
		if (value === undefined || value === null) {
			continue
		}

		if (!NON_SERIALIZABLE_PROPS.includes(typeof value)) {
			invalidTypes.push({ [key]: value })
		}
		let asString: string
		if (typeof value === 'string') {
			asString = value
		} else {
			asString = stringify(value)
		}
		if (asString.length > PROPERTY_MAX_LENGTH) {
			tooLong.push({ [key]: value })
			asString = asString.substring(0, PROPERTY_MAX_LENGTH)
		}

		stringifiedObj[key] = asString
	}

	// Skipping logging for 'session' type because they're generated by Highlight
	// (e.g. visited-url > 2000 characters)
	if (type !== 'session') {
		if (invalidTypes.length > 0) {
			console.warn(
				`Highlight was passed one or more ${type} properties not of type string, number, or boolean.`,
				invalidTypes,
			)
		}

		if (tooLong.length > 0) {
			console.warn(
				`Highlight was passed one or more ${type} properties exceeding 2000 characters, which will be truncated.`,
				tooLong,
			)
		}
	}

	return stringifiedObj
}

{
	let graphqlSDK: Sdk
	let backend: string
	let sessionSecureID: string
	let numberOfFailedRequests: number = 0
	let numberOfFailedPushPayloads: number = 0
	let hasStoppedRecording: boolean = false
	/**
	 * Counts the sessions this worker has served. Requests are stamped with the generation they
	 * were issued for, because a request outlives the session that issued it: it can still be in
	 * flight when recording stops, and what the backend answers about it says nothing about a
	 * session that has started since.
	 */
	let sessionGeneration: number = 0
	let debug: boolean = false
	let recordingStartTime: number = 0
	let logger = new Logger(false, '[worker]')
	const metricsPayload: {
		name: string
		value: number
		session_secure_id: string
		category: MetricCategory
		group: string
		timestamp: string
		tags: { name: string; value: string }[]
	}[] = []
	const pendingMessages: HighlightClientWorkerParams['message'][] = []

	const shouldSendRequest = (): boolean => {
		return (
			!hasStoppedRecording &&
			recordingStartTime !== 0 &&
			!!sessionSecureID?.length
		)
	}

	const addCustomEvent = <T>(tag: string, payload: T) => {
		worker.postMessage({
			response: {
				type: MessageType.CustomEvent,
				tag: tag,
				payload: payload,
			},
		})
	}

	/**
	 * Asks the client to stop recording and stops accepting work until it initializes again.
	 * Everything buffered here is dropped: the client stops handing us events, so a queue kept
	 * across a stop would only hold memory for data that will never be uploaded.
	 *
	 * Only the first caller is served. Requests already in flight when we stop keep failing and
	 * arrive here afterwards, and the client has nothing left to tear down by then.
	 */
	const stopRecording = (
		reason: StopReason,
		details?: Pick<
			StopEventResponse,
			'requestStart' | 'asyncEventsResponse'
		>,
	) => {
		if (hasStoppedRecording) {
			return
		}

		hasStoppedRecording = true
		pendingMessages.length = 0
		metricsPayload.length = 0

		worker.postMessage({
			response: {
				type: MessageType.Stop,
				reason,
				...details,
			},
		})
	}

	/**
	 * Accounts for a message we could not send. An unrecoverable failure ends recording right
	 * away, because the backend would reject every later request the same way. A recoverable one
	 * spends part of the retry budget, and exhausting that budget also ends recording: the client
	 * would otherwise keep producing payloads that pile up here unsent.
	 *
	 * @param generation which session the failed request was issued for.
	 */
	const handleFailedMessage = (e: unknown, generation: number) => {
		if (debug) {
			console.error(e)
		}

		// The session this request was issued for is over, and the one recording now neither sent
		// it nor has any reason to be stopped by it.
		if (generation !== sessionGeneration) {
			logger.log('Ignoring a failure from a session that already ended.')
			return
		}

		if (!isErrorRecoverable(e)) {
			console.warn(`Session data was rejected, stopping recording.`, e)
			stopRecording(StopReason.UnrecoverableError)
			return
		}

		numberOfFailedRequests += 1
		if (numberOfFailedRequests >= MAX_PUBLIC_GRAPH_RETRY_ATTEMPTS) {
			console.warn(
				`Session data failed to upload ${numberOfFailedRequests} times, stopping recording.`,
				e,
			)
			stopRecording(StopReason.RetriesExhausted)
		}
	}

	/**
	 * Accounts for a message we did send. The retry budget covers consecutive failures, so it
	 * starts over.
	 *
	 * @param generation which session the sent request was issued for.
	 */
	const handleSentMessage = (generation: number) => {
		// A request the backend accepted for a session that has ended says nothing about how the
		// one recording now is faring, and restoring its budget would postpone a stop it is due.
		if (generation !== sessionGeneration) {
			return
		}

		numberOfFailedRequests = 0
	}

	const processAsyncEventsMessage = async (msg: AsyncEventsMessage) => {
		const generation = sessionGeneration
		const {
			id,
			events,
			messages,
			errors,
			resourcesString,
			webSocketEventsString,
			hasSessionUnloaded,
			highlightLogs,
		} = msg

		const messagesString = stringify({ messages: messages })
		let payload: PushPayloadMutationVariables = {
			session_secure_id: sessionSecureID,
			payload_id: id.toString(),
			events: { events } as ReplayEventsInput,
			messages: messagesString,
			resources: resourcesString,
			web_socket_events: webSocketEventsString,
			errors,
			is_beacon: false,
			has_session_unloaded: hasSessionUnloaded,
		}
		if (highlightLogs) {
			payload.highlight_logs = highlightLogs
		}

		const { compressedBase64, bufferLength, compressedSize } =
			await payloadToBase64(payload)

		const response: AsyncEventsResponse = {
			type: MessageType.AsyncEvents,
			id,
			eventsSize: bufferLength,
			compressedSize: compressedBase64.length,
		}

		logger.log(
			`Pushing payload: ${JSON.stringify(
				{
					sessionSecureID,
					id,
					firstSID: Math.min(
						...(payload.events.events
							.map((e) => e?._sid)
							.filter((sid) => !!sid) as number[]),
					),
					eventsLength: payload.events.events.length,
					messagesLength: messages.length,
					resourcesLength: resourcesString.length,
					webSocketLength: webSocketEventsString.length,
					errorsLength: errors.length,
					bufLength: bufferLength,
					compressedLength: compressedSize,
					compressedBase64Length: compressedBase64.length,
				},
				undefined,
				2,
			)}`,
		)

		const pushPayload = graphqlSDK.PushSessionEvents({
			session_secure_id: sessionSecureID,
			payload_id: id.toString(),
			data: compressedBase64,
		})

		let pushMetrics: Promise<any> = Promise.resolve()
		if (metricsPayload.length) {
			pushMetrics = graphqlSDK.pushMetrics({
				metrics: metricsPayload,
			})
			// clear batched payload before yielding for network request
			metricsPayload.splice(0)
		}

		let requestStart: number = performance.now()
		const int = setInterval(() => {
			// A slow upload can outlast the session it belongs to, and how long it takes is then
			// no reason to stop the session recording now.
			if (generation !== sessionGeneration) {
				clearInterval(int)
				return
			}
			if (
				requestStart &&
				performance.now() - requestStart > UPLOAD_TIMEOUT
			) {
				console.warn(
					`Uploading pushPayload took too long, failure number #${numberOfFailedPushPayloads}.`,
				)
				numberOfFailedPushPayloads += 1
				clearInterval(int)

				if (
					numberOfFailedPushPayloads >=
					MAX_PUBLIC_GRAPH_RETRY_ATTEMPTS
				) {
					console.warn(
						`Uploading pushPayload took too long, stopping recording to avoid OOM.`,
					)

					stopRecording(StopReason.PushPayloadTimeout, {
						requestStart,
						asyncEventsResponse: response,
					})
				}
			}
		}, 100)
		try {
			await Promise.all([pushPayload, pushMetrics])
			if (
				// An upload that beat the timeout for a session that has ended says nothing
				// about how the one recording now is faring.
				generation === sessionGeneration &&
				numberOfFailedPushPayloads &&
				performance.now() - requestStart <= UPLOAD_TIMEOUT
			) {
				console.warn(
					`pushPayload succeeded after #${numberOfFailedPushPayloads} failures, resetting stop switch.`,
				)
				numberOfFailedPushPayloads = 0
			}
		} finally {
			requestStart = 0
			clearInterval(int)
		}

		// The client counts these bytes towards its next full snapshot, and they were recorded by
		// a session it is no longer replaying.
		if (generation !== sessionGeneration) {
			return
		}

		worker.postMessage({
			response,
		})
	}

	const processIdentifyMessage = async (msg: IdentifyMessage) => {
		const { userObject, userIdentifier, source } = msg
		if (source === 'segment') {
			addCustomEvent(
				'Segment Identify',
				stringify({ userIdentifier, ...userObject }),
			)
		} else {
			addCustomEvent(
				'Identify',
				stringify({ userIdentifier, ...userObject }),
			)
		}
		await graphqlSDK.identifySession({
			session_secure_id: sessionSecureID,
			user_identifier: userIdentifier,
			user_object: stringifyProperties(userObject, 'user'),
		})
		const sourceString = source === 'segment' ? source : 'default'
		logger.log(
			`Identify (${userIdentifier}, source: ${sourceString}) w/ obj: ${stringify(
				userObject,
			)} @ ${backend}`,
		)
	}

	const processPropertiesMessage = async (msg: PropertiesMessage) => {
		const { propertiesObject, propertyType } = msg
		let eventType: string
		if (propertyType?.type === 'session') {
			eventType = 'Session'
			// Session properties are custom properties that the Highlight snippet adds (visited-url, referrer, etc.)
			// These should be searchable but not part of `Track` timeline indicators
			await graphqlSDK.addSessionProperties({
				session_secure_id: sessionSecureID,
				properties_object: stringifyProperties(
					propertiesObject,
					'session',
				),
			})
		} else {
			// Track properties are properties that users define; rn, either through segment or manually.
			if (propertyType?.source === 'segment') {
				eventType = 'Segment'
			} else {
				eventType = 'Track'
			}
		}
		if (eventType !== 'Session') {
			addCustomEvent<string>(eventType, stringify(propertiesObject))
		}
		logger.log(
			`Adding ${eventType} Properties to session (${sessionSecureID}) w/ obj: ${JSON.stringify(
				propertiesObject,
			)} @ ${backend}`,
		)
	}

	const processMetricsMessage = async (msg: MetricsMessage) => {
		metricsPayload.push(
			...msg.metrics.map((m) => ({
				name: m.name,
				value: m.value,
				session_secure_id: sessionSecureID,
				category: m.category,
				group: m.group,
				timestamp: m.timestamp.toISOString(),
				tags: m.tags,
			})),
		)
	}

	const processFeedbackMessage = async (msg: FeedbackMessage) => {
		const { timestamp, verbatim, userEmail, userName } = msg
		await graphqlSDK.addSessionFeedback({
			session_secure_id: sessionSecureID,
			timestamp,
			verbatim,
			user_email: userEmail,
			user_name: userName,
		})
	}

	const processMessage = async (
		msg: HighlightClientWorkerParams['message'],
	) => {
		if (msg.type === MessageType.AsyncEvents) {
			await processAsyncEventsMessage(msg as AsyncEventsMessage)
		} else if (msg.type === MessageType.Identify) {
			await processIdentifyMessage(msg as IdentifyMessage)
		} else if (msg.type === MessageType.Properties) {
			await processPropertiesMessage(msg as PropertiesMessage)
		} else if (msg.type === MessageType.Metrics) {
			await processMetricsMessage(msg as MetricsMessage)
		} else if (msg.type === MessageType.Feedback) {
			await processFeedbackMessage(msg as FeedbackMessage)
		}
	}

	const drainPendingMessages = async () => {
		while (pendingMessages.length > 0 && shouldSendRequest()) {
			const msg = pendingMessages.shift()!
			const generation = sessionGeneration
			try {
				await processMessage(msg)
				handleSentMessage(generation)
			} catch (e) {
				handleFailedMessage(e, generation)
			}
		}
	}

	worker.onmessage = async function (e) {
		if (e.data.message.type === MessageType.Initialize) {
			backend = e.data.message.backend
			sessionSecureID = e.data.message.sessionSecureID
			debug = e.data.message.debug
			recordingStartTime = e.data.message.recordingStartTime
			logger.debug = debug
			// The client only initializes after `initializeSession` succeeded, so whatever made
			// us stop no longer applies.
			hasStoppedRecording = false
			sessionGeneration += 1
			numberOfFailedRequests = 0
			numberOfFailedPushPayloads = 0
			graphqlSDK = getSdk(
				new GraphQLClient(backend, {
					headers: {},
				}),
				getGraphQLRequestWrapper(),
			)

			await drainPendingMessages()
			return
		}

		// Handle Reset before shouldSendRequest - always execute immediately
		// This clears any pending data from a previous session on forceNew/sessionKey change
		if (e.data.message.type === MessageType.Reset) {
			pendingMessages.length = 0
			metricsPayload.length = 0
			numberOfFailedRequests = 0
			numberOfFailedPushPayloads = 0
			hasStoppedRecording = false
			sessionGeneration += 1
			// Reset sessionSecureID and recordingStartTime so that messages arriving
			// between Reset and new Initialize are queued rather than processed with
			// the old session SecureID
			sessionSecureID = ''
			recordingStartTime = 0
			return
		}

		// returns current worker state for testing/debugging
		if (e.data.message.type === MessageType.GetStatus) {
			worker.postMessage({
				response: {
					type: MessageType.GetStatus,
					pendingCount: pendingMessages.length,
					initialized: shouldSendRequest(),
				},
			})
			return
		}

		// Drop messages once recording has stopped: queueing them would grow without bound
		// because nothing is going to send them.
		if (hasStoppedRecording) {
			return
		}

		if (!shouldSendRequest()) {
			pendingMessages.push(e.data.message)
			return
		}

		const generation = sessionGeneration
		try {
			await processMessage(e.data.message)
			handleSentMessage(generation)
			await drainPendingMessages()
		} catch (err) {
			handleFailedMessage(err, generation)
		}
	}
}
