version: '2'

run:
    timeout: 2m

output:
    sort-order:
        - file

linters:
    default: none
    enable:
        - errcheck
        - govet
        - ineffassign
        - staticcheck
        - unused
    settings:
        staticcheck:
            checks: ['all', '-ST1000', '-ST1003']
