#!/usr/bin/env python3
"""
Generate buildTransitive/LaunchDarkly.SessionReplay.targets for the fat NuGet package.
Reads native-manifest.txt (one basename per line: foo.aar or bar.jar) and emits
explicit AndroidLibrary / AndroidJavaLibrary items (no globs).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def main() -> int:
	parser = argparse.ArgumentParser()
	parser.add_argument(
		"output_targets",
		type=Path,
		help="Path to write LaunchDarkly.SessionReplay.targets",
	)
	parser.add_argument(
		"manifest",
		type=Path,
		help="Path to native-manifest.txt (basenames, one per line)",
	)
	args = parser.parse_args()

	if not args.manifest.is_file():
		print(f"Manifest not found: {args.manifest}", file=sys.stderr)
		return 1

	lines = [
		l.strip()
		for l in args.manifest.read_text(encoding="utf-8").splitlines()
		if l.strip() and not l.strip().startswith("#")
	]

	aars = sorted(n for n in lines if n.lower().endswith(".aar"))
	jars = sorted(n for n in lines if n.lower().endswith(".jar"))
	unknown = sorted(
		n for n in lines if not n.lower().endswith((".aar", ".jar"))
	)
	if unknown:
		print(f"Unsupported entries in manifest (expected .aar/.jar): {unknown}", file=sys.stderr)
		return 1

	out: list[str] = [
		"<Project>",
		"\t<!--",
		"\t\tAuto-generated by GenerateConsumerBuildTransitive. Do not edit by hand.",
		"\t\tSource: NativeAndroidDeps.props + glob resolution at pack time.",
		"\t-->",
		'\t<ItemGroup Condition="$(TargetFramework.Contains(\'android\'))">',
	]

	for name in aars:
		out.append(
			f'\t\t<AndroidLibrary Include="$(MSBuildThisFileDirectory)../runtimes/android/native/{name}">'
		)
		out.append("\t\t\t<Bind>false</Bind>")
		out.append("\t\t\t<Visible>false</Visible>")
		out.append("\t\t</AndroidLibrary>")

	for name in jars:
		out.append(
			f'\t\t<AndroidJavaLibrary Include="$(MSBuildThisFileDirectory)../runtimes/android/native/{name}">'
		)
		out.append("\t\t\t<Bind>false</Bind>")
		out.append("\t\t\t<Visible>false</Visible>")
		out.append("\t\t</AndroidJavaLibrary>")

	out.extend(
		[
			"\t</ItemGroup>",
			'\t<ItemGroup Condition="$(TargetFramework.Contains(\'ios\'))">',
			'\t\t<NativeReference Include="$(MSBuildThisFileDirectory)../runtimes/ios/native/LDObserveBridge.xcframework">',
			"\t\t\t<Kind>Framework</Kind>",
			"\t\t\t<ForceLoad>true</ForceLoad>",
			"\t\t\t<SmartLink>true</SmartLink>",
			"\t\t</NativeReference>",
			"\t</ItemGroup>",
			"</Project>",
			"",
		]
	)

	args.output_targets.parent.mkdir(parents=True, exist_ok=True)
	args.output_targets.write_text("\n".join(out), encoding="utf-8")
	print(f"Wrote {args.output_targets} ({len(aars)} AAR, {len(jars)} JAR)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
