// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.launchdarkly.launchdarkly_flutter_observability

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class LDInstrumentationOptions (
  val networkRequests: Boolean? = null,
  val launchTimes: Boolean? = null,
  val crashReporting: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDInstrumentationOptions {
      val networkRequests = pigeonVar_list[0] as Boolean?
      val launchTimes = pigeonVar_list[1] as Boolean?
      val crashReporting = pigeonVar_list[2] as Boolean?
      return LDInstrumentationOptions(networkRequests, launchTimes, crashReporting)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      networkRequests,
      launchTimes,
      crashReporting,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDInstrumentationOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDTracesOptions (
  val includeErrors: Boolean? = null,
  val includeSpans: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDTracesOptions {
      val includeErrors = pigeonVar_list[0] as Boolean?
      val includeSpans = pigeonVar_list[1] as Boolean?
      return LDTracesOptions(includeErrors, includeSpans)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      includeErrors,
      includeSpans,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDTracesOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDAnalyticsOptions (
  val taps: Boolean? = null,
  val pageViews: Boolean? = null,
  val trackEvents: Boolean? = null,
  val appLifecycle: Boolean? = null,
  val appLaunch: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDAnalyticsOptions {
      val taps = pigeonVar_list[0] as Boolean?
      val pageViews = pigeonVar_list[1] as Boolean?
      val trackEvents = pigeonVar_list[2] as Boolean?
      val appLifecycle = pigeonVar_list[3] as Boolean?
      val appLaunch = pigeonVar_list[4] as Boolean?
      return LDAnalyticsOptions(taps, pageViews, trackEvents, appLifecycle, appLaunch)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taps,
      pageViews,
      trackEvents,
      appLifecycle,
      appLaunch,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDAnalyticsOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDObservabilityOptions (
  val isEnabled: Boolean? = null,
  val serviceName: String? = null,
  val serviceVersion: String? = null,
  val otlpEndpoint: String? = null,
  val backendUrl: String? = null,
  val contextFriendlyName: String? = null,
  val attributes: Map<String, Any?>? = null,
  val customHeaders: Map<String, String>? = null,
  val sessionBackgroundTimeoutMillis: Long? = null,
  val logsApiLevel: Long? = null,
  val traces: LDTracesOptions? = null,
  val metricsEnabled: Boolean? = null,
  val analytics: LDAnalyticsOptions? = null,
  val instrumentation: LDInstrumentationOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDObservabilityOptions {
      val isEnabled = pigeonVar_list[0] as Boolean?
      val serviceName = pigeonVar_list[1] as String?
      val serviceVersion = pigeonVar_list[2] as String?
      val otlpEndpoint = pigeonVar_list[3] as String?
      val backendUrl = pigeonVar_list[4] as String?
      val contextFriendlyName = pigeonVar_list[5] as String?
      val attributes = pigeonVar_list[6] as Map<String, Any?>?
      val customHeaders = pigeonVar_list[7] as Map<String, String>?
      val sessionBackgroundTimeoutMillis = pigeonVar_list[8] as Long?
      val logsApiLevel = pigeonVar_list[9] as Long?
      val traces = pigeonVar_list[10] as LDTracesOptions?
      val metricsEnabled = pigeonVar_list[11] as Boolean?
      val analytics = pigeonVar_list[12] as LDAnalyticsOptions?
      val instrumentation = pigeonVar_list[13] as LDInstrumentationOptions?
      return LDObservabilityOptions(isEnabled, serviceName, serviceVersion, otlpEndpoint, backendUrl, contextFriendlyName, attributes, customHeaders, sessionBackgroundTimeoutMillis, logsApiLevel, traces, metricsEnabled, analytics, instrumentation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isEnabled,
      serviceName,
      serviceVersion,
      otlpEndpoint,
      backendUrl,
      contextFriendlyName,
      attributes,
      customHeaders,
      sessionBackgroundTimeoutMillis,
      logsApiLevel,
      traces,
      metricsEnabled,
      analytics,
      instrumentation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDObservabilityOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDPrivacyOptions (
  val maskTextInputs: Boolean? = null,
  val maskWebViews: Boolean? = null,
  val maskLabels: Boolean? = null,
  val maskImages: Boolean? = null,
  val minimumAlpha: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDPrivacyOptions {
      val maskTextInputs = pigeonVar_list[0] as Boolean?
      val maskWebViews = pigeonVar_list[1] as Boolean?
      val maskLabels = pigeonVar_list[2] as Boolean?
      val maskImages = pigeonVar_list[3] as Boolean?
      val minimumAlpha = pigeonVar_list[4] as Double?
      return LDPrivacyOptions(maskTextInputs, maskWebViews, maskLabels, maskImages, minimumAlpha)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maskTextInputs,
      maskWebViews,
      maskLabels,
      maskImages,
      minimumAlpha,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDPrivacyOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDSessionReplayOptions (
  val isEnabled: Boolean? = null,
  val serviceName: String? = null,
  val frameRate: Double? = null,
  val privacy: LDPrivacyOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDSessionReplayOptions {
      val isEnabled = pigeonVar_list[0] as Boolean?
      val serviceName = pigeonVar_list[1] as String?
      val frameRate = pigeonVar_list[2] as Double?
      val privacy = pigeonVar_list[3] as LDPrivacyOptions?
      return LDSessionReplayOptions(isEnabled, serviceName, frameRate, privacy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isEnabled,
      serviceName,
      frameRate,
      privacy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDSessionReplayOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDStartResult (
  val nativeVersion: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDStartResult {
      val nativeVersion = pigeonVar_list[0] as String?
      return LDStartResult(nativeVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nativeVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDStartResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * An event recorded on a span, forwarded to the native tracer.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LDSpanEvent (
  val name: String? = null,
  val attributes: Map<String, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDSpanEvent {
      val name = pigeonVar_list[0] as String?
      val attributes = pigeonVar_list[1] as Map<String, Any?>?
      return LDSpanEvent(name, attributes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      attributes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDSpanEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A completed Dart span, forwarded to the native tracer so the native
 * pipeline re-creates it (stamping `session.id`, sampling, batching).
 *
 * Mirrors the data carried by MAUI's `TraceBuilderAdapter`
 * (`sdk/@launchdarkly/mobile-dotnet/observability/bridge/TraceBuilderAdapter.cs`).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LDSpanData (
  val name: String? = null,
  /** Span start as epoch seconds. */
  val startTimeSeconds: Double? = null,
  /** Span end as epoch seconds. */
  val endTimeSeconds: Double? = null,
  /** 32-char hex trace id. */
  val traceId: String? = null,
  /** 16-char hex span id. */
  val spanId: String? = null,
  /** 16-char hex parent span id, or empty for a root span. */
  val parentSpanId: String? = null,
  val attributes: Map<String, Any?>? = null,
  val events: List<LDSpanEvent?>? = null,
  /** 0 = unset, 1 = ok, 2 = error. */
  val statusCode: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDSpanData {
      val name = pigeonVar_list[0] as String?
      val startTimeSeconds = pigeonVar_list[1] as Double?
      val endTimeSeconds = pigeonVar_list[2] as Double?
      val traceId = pigeonVar_list[3] as String?
      val spanId = pigeonVar_list[4] as String?
      val parentSpanId = pigeonVar_list[5] as String?
      val attributes = pigeonVar_list[6] as Map<String, Any?>?
      val events = pigeonVar_list[7] as List<LDSpanEvent?>?
      val statusCode = pigeonVar_list[8] as Long?
      return LDSpanData(name, startTimeSeconds, endTimeSeconds, traceId, spanId, parentSpanId, attributes, events, statusCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      startTimeSeconds,
      endTimeSeconds,
      traceId,
      spanId,
      parentSpanId,
      attributes,
      events,
      statusCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDSpanData) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A log record forwarded to the native logger so it is emitted as a real
 * OpenTelemetry `LogRecord` (stamped with `session.id` and correlated with
 * the active span).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LDLogRecord (
  val message: String? = null,
  /** OpenTelemetry severity number (e.g. 9 = INFO, 13 = WARN, 17 = ERROR). */
  val severityNumber: Long? = null,
  /** 32-char hex trace id of the active span, or null when none. */
  val traceId: String? = null,
  /** 16-char hex span id of the active span, or null when none. */
  val spanId: String? = null,
  val attributes: Map<String, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDLogRecord {
      val message = pigeonVar_list[0] as String?
      val severityNumber = pigeonVar_list[1] as Long?
      val traceId = pigeonVar_list[2] as String?
      val spanId = pigeonVar_list[3] as String?
      val attributes = pigeonVar_list[4] as Map<String, Any?>?
      return LDLogRecord(message, severityNumber, traceId, spanId, attributes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
      severityNumber,
      traceId,
      spanId,
      attributes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDLogRecord) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDInstrumentationOptions.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDTracesOptions.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDAnalyticsOptions.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDObservabilityOptions.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDPrivacyOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDSessionReplayOptions.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDStartResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDSpanEvent.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDSpanData.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDLogRecord.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LDInstrumentationOptions -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LDTracesOptions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LDAnalyticsOptions -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is LDObservabilityOptions -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is LDPrivacyOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is LDSessionReplayOptions -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is LDStartResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is LDSpanEvent -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is LDSpanData -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is LDLogRecord -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LDNativeApi {
  fun start(mobileKey: String, observability: LDObservabilityOptions, replay: LDSessionReplayOptions, observabilityVersion: String, callback: (Result<LDStartResult>) -> Unit)
  /**
   * Forwards completed Dart spans to the native tracer. Native re-creates each
   * span so the native pipeline stamps `session.id` and exports it.
   */
  fun exportSpans(spans: List<LDSpanData>)
  /**
   * Forwards a Dart log to the native logger so it is emitted as a native
   * `LogRecord` with `session.id` and trace/span correlation.
   */
  fun recordLog(log: LDLogRecord)
  /**
   * Forwards a custom track event to the native observability SDK so it emits
   * the native `track` span (gated by `analytics.trackEvents`) and the Session
   * Replay `Track` timeline event (always). `data` carries the optional event
   * payload as a JSON object. `contextKeys` carries the evaluation context's
   * kind -> key pairs (from the LaunchDarkly client's `afterTrack` hook) so the
   * native `track` span is attributed to the same context the web SDK records;
   * only the span is annotated, not the Session Replay `Track` payload.
   */
  fun track(key: String, data: Map<String, Any?>?, metricValue: Double?, contextKeys: Map<String, String>?)
  /**
   * Forwards an `identify` to the native observability SDK and Session Replay.
   * Native observability caches `contextKeys` so manual `LDObserve.track` calls
   * (which carry no context) are attributed to the active context, and Session
   * Replay records who the user is on the active recording. `contextKeys`
   * carries the context's kind -> key pairs, `canonicalKey` the fully-qualified
   * key, and `completed` whether the identify finished successfully (native
   * ignores incomplete identifies). Mirrors MAUI's
   * `ObservabilityHook.AfterIdentify` /  `SessionReplayHook.AfterIdentify`.
   */
  fun identify(contextKeys: Map<String, String>, canonicalKey: String, completed: Boolean)

  companion object {
    /** The codec used by LDNativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `LDNativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LDNativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mobileKeyArg = args[0] as String
            val observabilityArg = args[1] as LDObservabilityOptions
            val replayArg = args[2] as LDSessionReplayOptions
            val observabilityVersionArg = args[3] as String
            api.start(mobileKeyArg, observabilityArg, replayArg, observabilityVersionArg) { result: Result<LDStartResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.exportSpans$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spansArg = args[0] as List<LDSpanData>
            val wrapped: List<Any?> = try {
              api.exportSpans(spansArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.recordLog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val logArg = args[0] as LDLogRecord
            val wrapped: List<Any?> = try {
              api.recordLog(logArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.track$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val dataArg = args[1] as Map<String, Any?>?
            val metricValueArg = args[2] as Double?
            val contextKeysArg = args[3] as Map<String, String>?
            val wrapped: List<Any?> = try {
              api.track(keyArg, dataArg, metricValueArg, contextKeysArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.identify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contextKeysArg = args[0] as Map<String, String>
            val canonicalKeyArg = args[1] as String
            val completedArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              api.identify(contextKeysArg, canonicalKeyArg, completedArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
