// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.launchdarkly.launchdarkly_flutter_observability

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class LDInstrumentationOptions (
  val networkRequests: Boolean? = null,
  val launchTimes: Boolean? = null,
  val crashReporting: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDInstrumentationOptions {
      val networkRequests = pigeonVar_list[0] as Boolean?
      val launchTimes = pigeonVar_list[1] as Boolean?
      val crashReporting = pigeonVar_list[2] as Boolean?
      return LDInstrumentationOptions(networkRequests, launchTimes, crashReporting)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      networkRequests,
      launchTimes,
      crashReporting,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDInstrumentationOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDTracesOptions (
  val includeErrors: Boolean? = null,
  val includeSpans: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDTracesOptions {
      val includeErrors = pigeonVar_list[0] as Boolean?
      val includeSpans = pigeonVar_list[1] as Boolean?
      return LDTracesOptions(includeErrors, includeSpans)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      includeErrors,
      includeSpans,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDTracesOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDAnalyticsOptions (
  val taps: Boolean? = null,
  val pageViews: Boolean? = null,
  val trackEvents: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDAnalyticsOptions {
      val taps = pigeonVar_list[0] as Boolean?
      val pageViews = pigeonVar_list[1] as Boolean?
      val trackEvents = pigeonVar_list[2] as Boolean?
      return LDAnalyticsOptions(taps, pageViews, trackEvents)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taps,
      pageViews,
      trackEvents,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDAnalyticsOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDObservabilityOptions (
  val isEnabled: Boolean? = null,
  val serviceName: String? = null,
  val serviceVersion: String? = null,
  val otlpEndpoint: String? = null,
  val backendUrl: String? = null,
  val contextFriendlyName: String? = null,
  val attributes: Map<String, Any?>? = null,
  val customHeaders: Map<String, String>? = null,
  val sessionBackgroundTimeoutMillis: Long? = null,
  val logsApiLevel: Long? = null,
  val traces: LDTracesOptions? = null,
  val metricsEnabled: Boolean? = null,
  val analytics: LDAnalyticsOptions? = null,
  val instrumentation: LDInstrumentationOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDObservabilityOptions {
      val isEnabled = pigeonVar_list[0] as Boolean?
      val serviceName = pigeonVar_list[1] as String?
      val serviceVersion = pigeonVar_list[2] as String?
      val otlpEndpoint = pigeonVar_list[3] as String?
      val backendUrl = pigeonVar_list[4] as String?
      val contextFriendlyName = pigeonVar_list[5] as String?
      val attributes = pigeonVar_list[6] as Map<String, Any?>?
      val customHeaders = pigeonVar_list[7] as Map<String, String>?
      val sessionBackgroundTimeoutMillis = pigeonVar_list[8] as Long?
      val logsApiLevel = pigeonVar_list[9] as Long?
      val traces = pigeonVar_list[10] as LDTracesOptions?
      val metricsEnabled = pigeonVar_list[11] as Boolean?
      val analytics = pigeonVar_list[12] as LDAnalyticsOptions?
      val instrumentation = pigeonVar_list[13] as LDInstrumentationOptions?
      return LDObservabilityOptions(isEnabled, serviceName, serviceVersion, otlpEndpoint, backendUrl, contextFriendlyName, attributes, customHeaders, sessionBackgroundTimeoutMillis, logsApiLevel, traces, metricsEnabled, analytics, instrumentation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isEnabled,
      serviceName,
      serviceVersion,
      otlpEndpoint,
      backendUrl,
      contextFriendlyName,
      attributes,
      customHeaders,
      sessionBackgroundTimeoutMillis,
      logsApiLevel,
      traces,
      metricsEnabled,
      analytics,
      instrumentation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDObservabilityOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDPrivacyOptions (
  val maskTextInputs: Boolean? = null,
  val maskWebViews: Boolean? = null,
  val maskLabels: Boolean? = null,
  val maskImages: Boolean? = null,
  val minimumAlpha: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDPrivacyOptions {
      val maskTextInputs = pigeonVar_list[0] as Boolean?
      val maskWebViews = pigeonVar_list[1] as Boolean?
      val maskLabels = pigeonVar_list[2] as Boolean?
      val maskImages = pigeonVar_list[3] as Boolean?
      val minimumAlpha = pigeonVar_list[4] as Double?
      return LDPrivacyOptions(maskTextInputs, maskWebViews, maskLabels, maskImages, minimumAlpha)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maskTextInputs,
      maskWebViews,
      maskLabels,
      maskImages,
      minimumAlpha,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDPrivacyOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDSessionReplayOptions (
  val isEnabled: Boolean? = null,
  val serviceName: String? = null,
  val frameRate: Double? = null,
  val privacy: LDPrivacyOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDSessionReplayOptions {
      val isEnabled = pigeonVar_list[0] as Boolean?
      val serviceName = pigeonVar_list[1] as String?
      val frameRate = pigeonVar_list[2] as Double?
      val privacy = pigeonVar_list[3] as LDPrivacyOptions?
      return LDSessionReplayOptions(isEnabled, serviceName, frameRate, privacy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isEnabled,
      serviceName,
      frameRate,
      privacy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDSessionReplayOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LDStartResult (
  val nativeVersion: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LDStartResult {
      val nativeVersion = pigeonVar_list[0] as String?
      return LDStartResult(nativeVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nativeVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LDStartResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDInstrumentationOptions.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDTracesOptions.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDAnalyticsOptions.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDObservabilityOptions.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDPrivacyOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDSessionReplayOptions.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LDStartResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LDInstrumentationOptions -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LDTracesOptions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LDAnalyticsOptions -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is LDObservabilityOptions -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is LDPrivacyOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is LDSessionReplayOptions -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is LDStartResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LDNativeApi {
  fun start(mobileKey: String, observability: LDObservabilityOptions, replay: LDSessionReplayOptions, observabilityVersion: String, callback: (Result<LDStartResult>) -> Unit)

  companion object {
    /** The codec used by LDNativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `LDNativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LDNativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mobileKeyArg = args[0] as String
            val observabilityArg = args[1] as LDObservabilityOptions
            val replayArg = args[2] as LDSessionReplayOptions
            val observabilityVersionArg = args[3] as String
            api.start(mobileKeyArg, observabilityArg, replayArg, observabilityVersionArg) { result: Result<LDStartResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
