// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

class LDInstrumentationOptions {
  LDInstrumentationOptions({
    this.networkRequests,
    this.launchTimes,
    this.crashReporting,
  });

  bool? networkRequests;

  bool? launchTimes;

  bool? crashReporting;

  List<Object?> _toList() {
    return <Object?>[networkRequests, launchTimes, crashReporting];
  }

  Object encode() {
    return _toList();
  }

  static LDInstrumentationOptions decode(Object result) {
    result as List<Object?>;
    return LDInstrumentationOptions(
      networkRequests: result[0] as bool?,
      launchTimes: result[1] as bool?,
      crashReporting: result[2] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDInstrumentationOptions ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LDTracesOptions {
  LDTracesOptions({this.includeErrors, this.includeSpans});

  bool? includeErrors;

  bool? includeSpans;

  List<Object?> _toList() {
    return <Object?>[includeErrors, includeSpans];
  }

  Object encode() {
    return _toList();
  }

  static LDTracesOptions decode(Object result) {
    result as List<Object?>;
    return LDTracesOptions(
      includeErrors: result[0] as bool?,
      includeSpans: result[1] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDTracesOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LDAnalyticsOptions {
  LDAnalyticsOptions({
    this.taps,
    this.pageViews,
    this.trackEvents,
    this.appLifecycle,
    this.appLaunch,
  });

  bool? taps;

  bool? pageViews;

  bool? trackEvents;

  bool? appLifecycle;

  bool? appLaunch;

  List<Object?> _toList() {
    return <Object?>[taps, pageViews, trackEvents, appLifecycle, appLaunch];
  }

  Object encode() {
    return _toList();
  }

  static LDAnalyticsOptions decode(Object result) {
    result as List<Object?>;
    return LDAnalyticsOptions(
      taps: result[0] as bool?,
      pageViews: result[1] as bool?,
      trackEvents: result[2] as bool?,
      appLifecycle: result[3] as bool?,
      appLaunch: result[4] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDAnalyticsOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LDObservabilityOptions {
  LDObservabilityOptions({
    this.isEnabled,
    this.serviceName,
    this.serviceVersion,
    this.otlpEndpoint,
    this.backendUrl,
    this.contextFriendlyName,
    this.attributes,
    this.customHeaders,
    this.sessionBackgroundTimeoutMillis,
    this.logsApiLevel,
    this.traces,
    this.metricsEnabled,
    this.analytics,
    this.instrumentation,
  });

  bool? isEnabled;

  String? serviceName;

  String? serviceVersion;

  String? otlpEndpoint;

  String? backendUrl;

  String? contextFriendlyName;

  Map<String, Object?>? attributes;

  Map<String, String>? customHeaders;

  int? sessionBackgroundTimeoutMillis;

  int? logsApiLevel;

  LDTracesOptions? traces;

  bool? metricsEnabled;

  LDAnalyticsOptions? analytics;

  LDInstrumentationOptions? instrumentation;

  List<Object?> _toList() {
    return <Object?>[
      isEnabled,
      serviceName,
      serviceVersion,
      otlpEndpoint,
      backendUrl,
      contextFriendlyName,
      attributes,
      customHeaders,
      sessionBackgroundTimeoutMillis,
      logsApiLevel,
      traces,
      metricsEnabled,
      analytics,
      instrumentation,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LDObservabilityOptions decode(Object result) {
    result as List<Object?>;
    return LDObservabilityOptions(
      isEnabled: result[0] as bool?,
      serviceName: result[1] as String?,
      serviceVersion: result[2] as String?,
      otlpEndpoint: result[3] as String?,
      backendUrl: result[4] as String?,
      contextFriendlyName: result[5] as String?,
      attributes: (result[6] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
      customHeaders: (result[7] as Map<Object?, Object?>?)
          ?.cast<String, String>(),
      sessionBackgroundTimeoutMillis: result[8] as int?,
      logsApiLevel: result[9] as int?,
      traces: result[10] as LDTracesOptions?,
      metricsEnabled: result[11] as bool?,
      analytics: result[12] as LDAnalyticsOptions?,
      instrumentation: result[13] as LDInstrumentationOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDObservabilityOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LDPrivacyOptions {
  LDPrivacyOptions({
    this.maskTextInputs,
    this.maskWebViews,
    this.maskLabels,
    this.maskImages,
    this.minimumAlpha,
  });

  bool? maskTextInputs;

  bool? maskWebViews;

  bool? maskLabels;

  bool? maskImages;

  double? minimumAlpha;

  List<Object?> _toList() {
    return <Object?>[
      maskTextInputs,
      maskWebViews,
      maskLabels,
      maskImages,
      minimumAlpha,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LDPrivacyOptions decode(Object result) {
    result as List<Object?>;
    return LDPrivacyOptions(
      maskTextInputs: result[0] as bool?,
      maskWebViews: result[1] as bool?,
      maskLabels: result[2] as bool?,
      maskImages: result[3] as bool?,
      minimumAlpha: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDPrivacyOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LDSessionReplayOptions {
  LDSessionReplayOptions({
    this.isEnabled,
    this.serviceName,
    this.frameRate,
    this.scale,
    this.privacy,
  });

  bool? isEnabled;

  String? serviceName;

  double? frameRate;

  double? scale;

  LDPrivacyOptions? privacy;

  List<Object?> _toList() {
    return <Object?>[isEnabled, serviceName, frameRate, scale, privacy];
  }

  Object encode() {
    return _toList();
  }

  static LDSessionReplayOptions decode(Object result) {
    result as List<Object?>;
    return LDSessionReplayOptions(
      isEnabled: result[0] as bool?,
      serviceName: result[1] as String?,
      frameRate: result[2] as double?,
      scale: result[3] as double?,
      privacy: result[4] as LDPrivacyOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDSessionReplayOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LDStartResult {
  LDStartResult({this.nativeVersion});

  String? nativeVersion;

  List<Object?> _toList() {
    return <Object?>[nativeVersion];
  }

  Object encode() {
    return _toList();
  }

  static LDStartResult decode(Object result) {
    result as List<Object?>;
    return LDStartResult(nativeVersion: result[0] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDStartResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// An event recorded on a span, forwarded to the native tracer.
class LDSpanEvent {
  LDSpanEvent({this.name, this.attributes});

  String? name;

  Map<String, Object?>? attributes;

  List<Object?> _toList() {
    return <Object?>[name, attributes];
  }

  Object encode() {
    return _toList();
  }

  static LDSpanEvent decode(Object result) {
    result as List<Object?>;
    return LDSpanEvent(
      name: result[0] as String?,
      attributes: (result[1] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDSpanEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// A completed Dart span, forwarded to the native tracer so the native
/// pipeline re-creates it (stamping `session.id`, sampling, batching).
///
/// Mirrors the data carried by MAUI's `TraceBuilderAdapter`
/// (`sdk/@launchdarkly/mobile-dotnet/observability/bridge/TraceBuilderAdapter.cs`).
class LDSpanData {
  LDSpanData({
    this.name,
    this.startTimeSeconds,
    this.endTimeSeconds,
    this.traceId,
    this.spanId,
    this.parentSpanId,
    this.attributes,
    this.events,
    this.statusCode,
  });

  String? name;

  /// Span start as epoch seconds.
  double? startTimeSeconds;

  /// Span end as epoch seconds.
  double? endTimeSeconds;

  /// 32-char hex trace id.
  String? traceId;

  /// 16-char hex span id.
  String? spanId;

  /// 16-char hex parent span id, or empty for a root span.
  String? parentSpanId;

  Map<String, Object?>? attributes;

  List<LDSpanEvent?>? events;

  /// 0 = unset, 1 = ok, 2 = error.
  int? statusCode;

  List<Object?> _toList() {
    return <Object?>[
      name,
      startTimeSeconds,
      endTimeSeconds,
      traceId,
      spanId,
      parentSpanId,
      attributes,
      events,
      statusCode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LDSpanData decode(Object result) {
    result as List<Object?>;
    return LDSpanData(
      name: result[0] as String?,
      startTimeSeconds: result[1] as double?,
      endTimeSeconds: result[2] as double?,
      traceId: result[3] as String?,
      spanId: result[4] as String?,
      parentSpanId: result[5] as String?,
      attributes: (result[6] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
      events: (result[7] as List<Object?>?)?.cast<LDSpanEvent?>(),
      statusCode: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDSpanData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// A log record forwarded to the native logger so it is emitted as a real
/// OpenTelemetry `LogRecord` (stamped with `session.id` and correlated with
/// the active span).
class LDLogRecord {
  LDLogRecord({
    this.message,
    this.severityNumber,
    this.traceId,
    this.spanId,
    this.attributes,
  });

  String? message;

  /// OpenTelemetry severity number (e.g. 9 = INFO, 13 = WARN, 17 = ERROR).
  int? severityNumber;

  /// 32-char hex trace id of the active span, or null when none.
  String? traceId;

  /// 16-char hex span id of the active span, or null when none.
  String? spanId;

  Map<String, Object?>? attributes;

  List<Object?> _toList() {
    return <Object?>[message, severityNumber, traceId, spanId, attributes];
  }

  Object encode() {
    return _toList();
  }

  static LDLogRecord decode(Object result) {
    result as List<Object?>;
    return LDLogRecord(
      message: result[0] as String?,
      severityNumber: result[1] as int?,
      traceId: result[2] as String?,
      spanId: result[3] as String?,
      attributes: (result[4] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LDLogRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is LDInstrumentationOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is LDTracesOptions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is LDAnalyticsOptions) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is LDObservabilityOptions) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is LDPrivacyOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is LDSessionReplayOptions) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is LDStartResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is LDSpanEvent) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is LDSpanData) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is LDLogRecord) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return LDInstrumentationOptions.decode(readValue(buffer)!);
      case 130:
        return LDTracesOptions.decode(readValue(buffer)!);
      case 131:
        return LDAnalyticsOptions.decode(readValue(buffer)!);
      case 132:
        return LDObservabilityOptions.decode(readValue(buffer)!);
      case 133:
        return LDPrivacyOptions.decode(readValue(buffer)!);
      case 134:
        return LDSessionReplayOptions.decode(readValue(buffer)!);
      case 135:
        return LDStartResult.decode(readValue(buffer)!);
      case 136:
        return LDSpanEvent.decode(readValue(buffer)!);
      case 137:
        return LDSpanData.decode(readValue(buffer)!);
      case 138:
        return LDLogRecord.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LDNativeApi {
  /// Constructor for [LDNativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LDNativeApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<LDStartResult> start(
    String mobileKey,
    LDObservabilityOptions observability,
    LDSessionReplayOptions replay,
    String observabilityVersion,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.start$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[mobileKey, observability, replay, observabilityVersion],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as LDStartResult?)!;
    }
  }

  /// Forwards completed Dart spans to the native tracer. Native re-creates each
  /// span so the native pipeline stamps `session.id` and exports it.
  Future<void> exportSpans(List<LDSpanData> spans) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.exportSpans$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[spans],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Forwards a Dart log to the native logger so it is emitted as a native
  /// `LogRecord` with `session.id` and trace/span correlation.
  Future<void> recordLog(LDLogRecord log) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.recordLog$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[log],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Forwards a custom track event to the native observability SDK so it emits
  /// the native `track` span (gated by `analytics.trackEvents`) and the Session
  /// Replay `Track` timeline event (always). `data` carries the optional event
  /// payload as a JSON object. `contextKeys` carries the evaluation context's
  /// kind -> key pairs (from the LaunchDarkly client's `afterTrack` hook) so the
  /// native `track` span is attributed to the same context the web SDK records;
  /// only the span is annotated, not the Session Replay `Track` payload.
  Future<void> track(
    String key,
    Map<String, Object?>? data,
    double? metricValue,
    Map<String, String>? contextKeys,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.track$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, data, metricValue, contextKeys],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Forwards an `identify` to the native observability SDK and Session Replay.
  /// Native observability caches `contextKeys` so manual `LDObserve.track` calls
  /// (which carry no context) are attributed to the active context, and Session
  /// Replay records who the user is on the active recording. `contextKeys`
  /// carries the context's kind -> key pairs, `canonicalKey` the fully-qualified
  /// key, and `completed` whether the identify finished successfully (native
  /// ignores incomplete identifies). Mirrors MAUI's
  /// `ObservabilityHook.AfterIdentify` /  `SessionReplayHook.AfterIdentify`.
  Future<void> identify(
    Map<String, String> contextKeys,
    String canonicalKey,
    bool completed,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.launchdarkly_flutter_observability.LDNativeApi.identify$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[contextKeys, canonicalKey, completed],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
