export { RECORD_ATTRIBUTE } from './instrumentation/constants'
export { CustomTraceContextPropagator } from './instrumentation/propagator'
export type { TracingOrigins } from './instrumentation/types'
export { getCorsUrlsPattern, getSpanName } from './instrumentation/utils'
export { CustomSampler } from './sampling/CustomSampler'
export { ExportSampler } from './sampling/ExportSampler'
export { SamplingResult } from './sampling/ExportSampler'
export { sampleSpans } from './sampling/sampleSpans'
export { sampleLogs } from './sampling/sampleLogs'
export { getSamplingConfig } from './sampling/getSamplingConfig'
