export { RECORD_ATTRIBUTE } from './instrumentation/constants'
export { CustomTraceContextPropagator } from './instrumentation/propagator'
export type { TracingOrigins } from './instrumentation/types'
export { getCorsUrlsPattern, getSpanName } from './instrumentation/utils'
export * from './sampling'
