name: 'Publish Android SDK'
description: 'Build and publish Android SDK packages to Maven Central'

inputs:
    workspace-path:
        description: 'Path to the Android SDK workspace'
        required: true
        default: 'sdk/@launchdarkly/observability-android'
    java_version:
        description: 'The Java version to use.'
        required: false
        default: '17'
    java_distribution:
        description: 'The Java distribution to use.'
        required: false
        default: 'temurin'
    aws-role-arn:
        description: 'AWS role ARN for accessing secrets'
        required: true
    dry-run:
        description: 'Whether to run the publish in dry-run mode'
        required: false
        default: 'false'

outputs:
    package-hashes:
        description: 'Base64 encoded SHA256 hashes of published packages'
        value: ${{ steps.package-hashes.outputs.package-hashes }}

runs:
    using: 'composite'
    steps:
        - name: Checkoutf
          uses: actions/checkout@v4
          with:
            ref: ta/O11Y-388/setup-build-publish-actions

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: ${{ inputs.java_distribution }}
            java-version: ${{ inputs.java_version }}

        - name: Setup Android SDK
          uses: android-actions/setup-android@v3

        - name: Build
          shell: bash
          working-directory: ${{ inputs.workspace-path }}
          id: build
          run: ./gradlew build jar

        - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.1.0
          name: Get secrets
          with:
            aws_assume_role: ${{ inputs.aws-role-arn }}
            ssm_parameter_pairs: '/production/common/releasing/sonatype/central/username = SONATYPE_USER_NAME,
            /production/common/releasing/sonatype/central/password = SONATYPE_PASSWORD,
            /production/common/releasing/android_code_signing/private_key_id = SIGNING_KEY_ID,
            /production/common/releasing/android_code_signing/private_key_passphrase = SIGNING_KEY_PASSPHRASE'
            s3_path_pairs: 'launchdarkly-releaser/android/code-signing-keyring.gpg = code-signing-keyring.gpg'

        - name: Publish Library
          shell: bash
          if: ${{ inputs.dry_run == 'false' }}
          env:
            LD_RELEASE_IS_PRERELEASE: ${{ inputs.prerelease }}
            SIGNING_KEY_ID: ${{ inputs.signing_key_id }}
            SIGNING_KEY_PASSPHRASE: ${{ inputs.signing_key_passphrase }}
            SIGNING_SECRET_KEY_RING_FILE: ${{ inputs.code_signing_keyring }}
            SONATYPE_USER_NAME: ${{ inputs.sonatype_username }}
            SONATYPE_PASSWORD: ${{ inputs.sonatype_password }}
          run: source $GITHUB_ACTION_PATH/publish.sh

        - name: Dry Run Publish Library
          shell: bash
          if: ${{ inputs.dry_run == 'true' }}
          run: echo "Dry run. Not publishing."
