name: Dependency Scan

permissions:
    contents: read

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    dependency-scan:
        uses: launchdarkly/gh-actions/.github/workflows/dependency-scan.yml@main
        with:
            types: 'nodejs'
            runs-on: 'ubuntu-latest-8-cores'
        secrets: inherit
