name: Dependency Scan
permissions:
    contents: read

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    generate-nodejs-sbom:
        runs-on: ubuntu-latest-8-cores
        env:
            NODE_OPTIONS: '--max-old-space-size=8192'
        steps:
            - uses: actions/checkout@v4

            - name: Generate SBOM
              uses: launchdarkly/gh-actions/actions/dependency-scan/generate-sbom@main
              with:
                  types: 'nodejs'
              timeout-minutes: 20

    evaluate-policy:
        runs-on: ubuntu-latest
        needs:
            - generate-nodejs-sbom
        steps:
            - uses: actions/checkout@v4

            - name: Evaluate SBOM Policy
              uses: launchdarkly/gh-actions/actions/dependency-scan/evaluate-policy@main
              with:
                  artifacts-pattern: bom-*
