# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
    workflow_dispatch:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
    schedule:
        - cron: '26 19 * * 1'

jobs:
    lint:
        name: DevSkim
        runs-on: ubuntu-22.04-8core-32gb
        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run DevSkim scanner
              uses: microsoft/DevSkim-Action@430c9d5fb2166a5b9e8b19791d895514adcb6271
              with:
                  ignore-globs: '**/otel/samples/**'

            - name: Upload DevSkim scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2
              with:
                  sarif_file: devskim-results.sarif
