name: .NET SDK

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'sdk/highlight-dotnet/**'
            - 'sdk/highlight-dotnet4/**'
            - '.github/workflows/dotnet.yml'

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    build-dotnet:
        name: ASP.NET Core SDK
        runs-on: ubuntu-22.04-8core-32gb
        defaults:
            run:
                working-directory: ./sdk/highlight-dotnet
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup .NET environment
              uses: actions/setup-dotnet@67a3573f04a4b92a75c0e6b09f8b2a1d8f96fb9a
              with:
                  dotnet-version: 8.x

            - name: Build solution and generate NuGet package
              run: dotnet pack -c Release -o out

            - name: Push generated package to NuGet registry
              if: github.ref == 'refs/heads/main'
              run: dotnet nuget push out/*.nupkg --skip-duplicate -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
              env:
                  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    build-dotnet4:
        name: ASP.NET4 SDK
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./sdk/highlight-dotnet4
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup dotnet
              uses: actions/setup-dotnet@67a3573f04a4b92a75c0e6b09f8b2a1d8f96fb9a
              with:
                  dotnet-version: 8.x

            - name: Setup dotnet
              uses: microsoft/setup-msbuild@6fb02220983dee4d3bb8319c7fa169b069e1f4c2

            - name: msbuild restore
              run: msbuild -t:Restore

            - name: msbuild pack
              run: msbuild -t:Pack -property:Configuration=Release

            - name: Push generated package to NuGet registry
              if: github.ref == 'refs/heads/main'
              run: |
                  nuget push bin\**\*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }} -SymbolApiKey ${{ secrets.NUGET_API_KEY }} -SkipDuplicate
