name: End to End Example Apps

on:
    push:
        branches: ['main']
    pull_request_target:
        types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    e2e-docker:
        name: E2E Dockerized Apps
        timeout-minutes: 60
        runs-on: ubuntu-22.04-8core-32gb
        strategy:
            matrix:
                app: ['dotnet', 'dotnet4', 'go', 'python', 'ruby']

        steps:
            - uses: actions/checkout@v4

            - name: Install poetry
              run: pipx install poetry

            - name: Install python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
                  cache: 'poetry'

            - name: Install dependencies
              working-directory: ./e2e/tests
              run: poetry install --all-extras

            - name: Start docker containers & run sdk e2e test
              working-directory: ./e2e/tests/src
              run: poetry run python app_runner.py ${{ matrix.app }}
