name: 'Elixir SDK code checks'

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'sdk/highlight-ex/**'
            - '.github/workflows/elixir-sdk.yml'

env:
    ELIXIR_VERSION: '1.13.4'
    OTP_VERSION: '25.0.1'

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    format:
        name: format elixir files
        runs-on: ubuntu-22.04-8core-32gb
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup Elixir
              uses: erlef/setup-beam@b84ff0173a4b1ccd8b8b8e4a9ac371c2a45f9c85
              with:
                  elixir-version: ${{ env.ELIXIR_VERSION }}
                  otp-version: ${{ env.OTP_VERSION }}
            - name: Format
              working-directory: sdk/highlight-ex
              run: mix format

    test:
        name: test package
        runs-on: ubuntu-22.04-8core-32gb
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup Elixir
              uses: erlef/setup-beam@b84ff0173a4b1ccd8b8b8e4a9ac371c2a45f9c85
              with:
                  elixir-version: ${{ env.ELIXIR_VERSION }}
                  otp-version: ${{ env.OTP_VERSION }}
            - name: Install Dependencies
              working-directory: sdk/highlight-ex
              run: mix deps.get
            - name: Run Tests
              working-directory: sdk/highlight-ex
              run: mix test

    publish:
        name: publish package
        runs-on: ubuntu-22.04-8core-32gb
        if: github.ref == 'ref/heads/main'
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup Elixir
              uses: erlef/setup-beam@b84ff0173a4b1ccd8b8b8e4a9ac371c2a45f9c85
              with:
                  elixir-version: ${{ env.ELIXIR_VERSION }}
                  otp-version: ${{ env.OTP_VERSION }}
            - name: Publish to Hex
              uses: synchronal/hex-publish-action@9e1b1776f5f9a5b5a2c1e54c1c60c7bbf9ea72d2
              with:
                  name: highlight
                  key: ${{ secrets.HEX_PM_KEY }}
                  tag-release: false
                  working-directory: sdk/highlight-ex
