name: 'Force pkg.go.dev release sync'

on:
    release:
        types:
            - created
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '**/v[0-9]+.[0-9]+.[0-9]+'

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    build:
        name: Renew documentation
        runs-on: ubuntu-22.04-8core-32gb
        steps:
            - name: Pull new module version
              uses: andrewslotin/go-proxy-pull-action@97435a544ec0915b6fef4afcda1705176f9d7e92
