name: Manual Publish Docs
on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    publish-docs:
        runs-on: ubuntu-22.04-8core-32gb
        steps:
            - run: git submodule update --init --recursive

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: 'yarn'

            - name: Install js dependencies
              run: yarn install --mode=skip-build
              env:
                  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

            - name: Build docs
              run: yarn docs --filter highlight.run

            - uses: launchdarkly/gh-actions/actions/publish-pages@publish-pages-v1.0.2
              name: 'Publish to Github pages'
              with:
                  docs_path: sdk/highlight-run/docs
                  output_path: packages/@launchdarkly/observability
                  github_token: ${{ secrets.GITHUB_TOKEN }}
