name: Manual Publish Package
on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: 'Is this a dry run. If so no package will be published.'
                type: boolean
                required: true
            prerelease:
                description: 'Is this a prerelease. If so, then the latest tag will not be updated in npm.'
                type: boolean
                required: true

permissions:
    id-token: write
    contents: write
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    publish-package:
        runs-on: ubuntu-latest
        steps:
            - uses: launchdarkly/common-actions/ssh-key-by-repo@main
              with:
                  repo_keys_map: |
                      {
                          "launchdarkly/rrweb": ${{ toJSON(secrets.LAUNCHDARKLY_RRWEB_DEPLOY_KEY) }}
                      }
            - uses: launchdarkly/common-actions/init@main
              env:
                  GITHUB_TOKEN: ${{ github.token }}
            - run: git submodule update --init --recursive

            - uses: actions/checkout@v4
              with:
                  path: gh-pages
                  ref: gh-pages

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: 'yarn'

            - name: Install js dependencies
              run: yarn

            - name: Build docs
              run: yarn docs

            - name: Publish
              shell: bash
              run: |
                  ./scripts/publish-npm.sh
              env:
                  LD_RELEASE_IS_PRERELEASE: ${{ inputs.prerelease }}
                  LD_RELEASE_IS_DRYRUN: ${{ inputs.dry-run }}
