name: Publish Docs

on:
    push:
        branches: ['main']

permissions:
    contents: write

jobs:
    publish-o11y-docs:
        concurrency: ${{ github.workflow }}-${{ github.ref }}-publish-o11y-docs
        name: Publish @launchdarkly/o11y Docs
        if: github.ref == 'refs/heads/main'
        uses: ./.github/workflows/manual-publish-docs.yml
        with:
            workspace_path: sdk/@launchdarkly/o11y

    publish-observability-node-docs:
        concurrency: ${{ github.workflow }}-${{ github.ref }}-publish-observability-node-docs
        # Run the docs publish after the @launchdarkly/o11y docs are published.
        needs: publish-o11y-docs
        # Runs the job even if the @launchdarkly/o11y docs publish fails.
        if: ${{ always() && !cancelled() && github.ref == 'refs/heads/main'}}
        name: Publish @launchdarkly/observability-node Docs
        uses: ./.github/workflows/manual-publish-docs.yml
        with:
            workspace_path: sdk/@launchdarkly/observability-node

    publish-observability-react-native-docs:
        concurrency: ${{ github.workflow }}-${{ github.ref }}-publish-observability-react-native-docs
        # Run the docs publish after the observability-node docs are published.
        needs: publish-observability-node-docs
        # Runs the job even if the observability-node docs publish fails.
        if: ${{ always() && !cancelled() && github.ref == 'refs/heads/main'}}
        name: Publish @launchdarkly/observability-react-native Docs
        uses: ./.github/workflows/manual-publish-docs.yml
        with:
            workspace_path: sdk/@launchdarkly/observability-react-native
