name: Python SDK

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'e2e/tests/**'
            - 'sdk/highlight-py/**'
            - '.github/workflows/python.yml'

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    build:
        permissions:
            id-token: write # for python PyPI OIDC login
            contents: write
            pull-requests: write
            repository-projects: write
        name: Python SDK
        runs-on: ubuntu-22.04-8core-32gb
        defaults:
            run:
                working-directory: ./sdk/highlight-py
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install poetry
              run: pipx install poetry
            - uses: actions/setup-python@7f4fc3e22c37d6ff65c4b91f7f3a4c76f9a1d1c7
              with:
                  python-version: '3.12'
                  cache: 'poetry'
            - run: poetry install --all-extras
            - name: Lint
              run: poetry run black --check .
            - name: Test
              run: poetry run pytest --cov=highlight_io --cov-branch --cov-report xml
            - name: Get Cover
              if: github.event_name == 'pull_request'
              uses: orgoro/coverage@b8b0b4e0b9a1cfb3f9a1ecfb8f28b9dea6e01e3a
              with:
                  coverageFile: ./sdk/highlight-py/coverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              run: poetry build
            - name: Validate PyProject
              working-directory: ./e2e/python/setuptools
              run: |
                  python -m pip install -U pip pip-tools;
                  python -m piptools compile --upgrade pyproject.toml;
            - name: Publish
              if: github.ref == 'refs/heads/main'
              uses: pypa/gh-action-pypi-publish@76f52bc88425d27c6beec496f5b2e5c0c4e8f5f0
              with:
                  packages-dir: ./sdk/highlight-py/dist/
                  skip-existing: true

    e2e:
        name: Validate E2E tests
        runs-on: ubuntu-22.04-8core-32gb
        defaults:
            run:
                working-directory: ./e2e/tests

        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install poetry
              run: pipx install poetry
            - uses: actions/setup-python@7f4fc3e22c37d6ff65c4b91f7f3a4c76f9a1d1c7
              with:
                  python-version: '3.10'
                  cache: 'poetry'
            - run: poetry install --all-extras
            - name: Lint
              run: poetry run black --check .
