name: Ruby SDK

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'sdk/highlight-ruby/**'
            - '.github/workflows/ruby.yml'

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    build:
        name: Ruby SDK
        runs-on: ubuntu-22.04-8core-32gb
        strategy:
            matrix:
                ruby: ['3.1', '3.3']
        defaults:
            run:
                working-directory: ./sdk/highlight-ruby/highlight
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
              id: filter
              with:
                  filters: |
                      ruby-changed:
                        - 'sdk/highlight-ruby/**'
            - name: Install Ruby
              uses: ruby/setup-ruby@9384f53a7f2c2a1e1e01dbd2b7c6a3d1b8f0d973
              with:
                  ruby-version: ${{ matrix.ruby }}
                  bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            - name: Install dependencies
              run: bundle install
            - name: Test
              run: bundle exec rake
            - name: Rubocop
              run: bundle exec rubocop
            - name: Publish to RubyGems
              if: github.ref == 'refs/heads/main' && matrix.ruby == '3.3' && steps.filter.outputs.ruby-changed == 'true'
              run: |
                  mkdir -p $HOME/.gem
                  touch $HOME/.gem/credentials
                  chmod 0600 $HOME/.gem/credentials
                  printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
                  gem build *.gemspec
                  gem push *.gem
              env:
                  RUBYGEMS_API_KEY: '${{secrets.RUBYGEMS_API_KEY}}'
    e2e:
        name: Rails Example App Tests
        runs-on: ubuntu-22.04-8core-32gb
        defaults:
            run:
                working-directory: ./e2e/ruby/rails/demo
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install Ruby
              uses: ruby/setup-ruby@9384f53a7f2c2a1e1e01dbd2b7c6a3d1b8f0d973
              with:
                  ruby-version: '3.3.4'
                  bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            - name: Install dependencies
              run: bundle install
            - name: Test
              run: bundle exec rake
            - name: Rubocop
              run: bundle exec rubocop
    e2e-api-only:
        name: Rails API-Only Example App Tests
        runs-on: ubuntu-22.04-8core-32gb
        defaults:
            run:
                working-directory: ./e2e/ruby/rails/api-only
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install Ruby
              uses: ruby/setup-ruby@9384f53a7f2c2a1e1e01dbd2b7c6a3d1b8f0d973
              with:
                  ruby-version: '3.3.4'
                  bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            - name: Install dependencies
              run: bundle install
            - name: Test
              run: bundle exec rake
