name: 'Rust SDK'

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'sdk/highlight-rust/**'
            - '.github/workflows/rust-sdk.yml'

defaults:
    run:
        working-directory: ./sdk/highlight-rust

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    build:
        name: Build
        runs-on: ubuntu-22.04-8core-32gb
        if: github.event_name == 'pull_request'
        defaults:
            run:
                working-directory: ./sdk/highlight-rust
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
              with:
                  toolchain: stable
                  override: true

            - name: Build crates
              uses: katyo/publish-crates@da3c314ce36e9d3f37a9be5602e9e77d45d12d94
              with:
                  path: ./sdk/highlight-rust/
                  dry-run: true
    publish:
        name: Publish
        runs-on: ubuntu-22.04-8core-32gb
        if: github.event_name == 'push'
        defaults:
            run:
                working-directory: ./sdk/highlight-rust
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
              with:
                  toolchain: stable
                  override: true

            - name: Publish crates
              uses: katyo/publish-crates@da3c314ce36e9d3f37a9be5602e9e77d45d12d94
              with:
                  path: ./sdk/highlight-rust/
                  registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
