name: Monorepo

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    yarn-monorepo:
        name: Build Yarn Turborepo
        timeout-minutes: 60
        runs-on: ubuntu-22.04-8core-32gb
        # configures turborepo Remote Caching
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        steps:
            - uses: launchdarkly/common-actions/ssh-key-by-repo@main
              with:
                  repo_keys_map: |
                      {
                        "launchdarkly/rrweb": ${{ toJSON(secrets.LAUNCHDARKLY_RRWEB_DEPLOY_KEY) }}
                      }
            - uses: launchdarkly/common-actions/init@main
              env:
                  GITHUB_TOKEN: ${{ github.token }}
            - run: git submodule update --init --recursive

            # automatically caches dependencies based on yarn.lock
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: 'yarn'

            - name: Install js dependencies
              run: yarn

            - name: Check yarn for duplicate deps
              run: yarn dedupe --check

            - name: Check formatting
              run: yarn format-check

            - name: Build & test (in a fork without doppler)
              run: yarn test
              env:
                  NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID: 1jdkoe52
                  REACT_APP_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
